### PR TITLE
refactoring packages to their specific subdomains

### PR DESCRIPTION
**Pull request by nykolaslima**
Created 2 subdomain packages: `message` and `strategy`

### CODE REVIEW

**Comment by garcia-jj** [comment]
This is a dangerous change because will break application that uses this classes in its current packages. I don't know if this is really necessary, since can add a compatibility break.

**Comment by nykolaslima** [comment]
Hum...that's right, we will break clients. But I think that as we grow this it will get confuse.

What do you think?

**Comment by garcia-jj** [comment]
The plugin have only eleven classes.

**Comment by nykolaslima** [comment]
@garcia-jj I agree with you. I think we don't need this for now. Thanks!

**Pull request closed without merging**
