### PR TITLE
adding onErrorSendBadRequest

### LINKED ISSUE #13: Support send bad request on errors
With VRaptor's Validator we can do:
`validator.onErrorSendBadRequest()`

We should be able to do the same with simple validator.

### PR DESCRIPTION
**Pull request by nykolaslima**
Closes #13

### CODE REVIEW

**Comment by nykolaslima** [comment]
This also closes #9 because we added the method `getErrors`

**Comment by Turini** [comment]
which method `getErrors`?

**Comment by nykolaslima** [comment]
Ops sorry.  `getErrors` is in this PR: https://github.com/caelum/vraptor-simple-validator/pull/16

**Comment by Turini** [comment]
Oh, ok! So this PR looks nice, merging here. Thanks

**Comment by nykolaslima** [comment]
@Turini @leocwolter Can you guys release a new version with those changes?

**Comment by Turini** [comment]
sure @nykolaslima, I'm doing it right now

**Comment by Turini** [comment]
it's done, in a few hours it will be available on maven (vs `4.1.0-RC3`)

**Comment by nykolaslima** [comment]
@Turini thank you!

**Pull request merged**
